server:
  port: 0
  context-path: /labs/ribbon-client/

management:
  security:
    enabled: false
security:
    basic:
        enabled: false

info:
  component: Ribbon Client

spring-discovery-client:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 5000


eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.int}}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/