server:
  port: 0
  context-path: /labs/discovery-client/

info:
  component: Eureka Discovery Client


management:
  security:
    enabled: false


eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

