server:
  port: ${PORT:8761}

info:
  component: Eureka Discovery Server


eureka:
#  datacenter: DC1
#  environment: local
#  shouldUseDns: false

  client:
    registerWithEureka: false
    fetchRegistry: true
    healthcheck:
      enabled: true

#  instance:
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
#    securePortEnabled: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: 0.85
    enableSelfPreservation: true


management:
  security:
    enabled: false
security:
    basic:
        enabled: false